apiVersion: build.openshift.io/v1
kind: BuildConfig
  name: test-app
  namespace: test-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: test-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/AlfredoPizarro/php-service.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.3-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: l6l3uz51h5bN2JYdjlOs
    type: GitHub
  - generic:
      secret: N3rXh3Bkxez0KvXJLkvY
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:b08209b2506392333b075c03f9be260de7b3ebda8315f44b89218c5ba074562d
    type: ImageChange
